# Домашнє завдання: Внесення оновлень в БД і робота з транзакціями

Це ДЗ передбачене під виконання на локальній машині. Виконання з Google Colab буде суттєво ускладнене.

## Підготовка
1. Переконайтесь, що у вас встановлены необхідні бібліотеки:
   ```bash
   pip install sqlalchemy pymysql pandas matplotlib seaborn python-dotenv
   ```

2. Створіть файл `.env` з параметрами підключення до бази даних classicmodels. Базу даних ви можете отримати через

  - docker-контейнер згідно існтрукції в [документі](https://www.notion.so/hannapylieva/Docker-1eb94835849480c9b2e7f5dc22ee4df9), також відео інструкції присутні на платформі - уроки "MySQL бази, клієнт для роботи з БД, Docker і ChatGPT для запитів" та "Як встановити Docker для роботи з базами даних без терміналу"
  - або встановивши локально цю БД - для цього перегляньте урок "Опціонально. Встановлення MySQL та  БД Сlassicmodels локально".
  
  Приклад `.env` файлу ми створювали в лекції. Ось його обовʼязкове наповнення:
    ```
    DB_HOST=your_host
    DB_PORT=3306 або 3307 - той, який Ви налаштували
    DB_USER=your_username
    DB_PASSWORD=your_password
    DB_NAME=classicmodels
    ```
  Якщо ви створили цей файл під час перегляду лекції - **новий створювати не треба**. Замініть лише назву БД, або пропишіть назву в коді створення підключення (замість отримання назви цільової БД зі змінних оточення). Але переконайтесь, що до `.env` файл лежить в тій самій папці, що і цей ноутбук.

  **УВАГА!** НЕ копіюйте скрит для **створення** `.env` файлу. В лекції він наводиться для прикладу. І давалось пояснення, що в реальних проєктах ми НІКОЛИ не пишемо доступи до бази в коді. Копіювання скрипта для створення `.env` файлу сюди в ДЗ буде вважатись грубою помилкою і ми зніматимемо бали.

3. Налаштуйте підключення через SQLAlchemy до БД за прикладом в лекції.

Рекомендую вивести (відобразити) змінну engine після створення. Вона має бути не None! Якщо None - значить у Вас не підтягнулись налаштування з .env файла.

Ви також можете налаштувати параметри підключення до БД без .env файла, просто прописавши текстом в відповідних місцях. Це - не рекомендований підхід.


## Завдання

### Завдання 1: Оновлення інформації про клієнта (2 бали)

**Створіть функцію для оновлення контактної інформації клієнта за його номером** з наступними можливостями:
- Оновлення телефону клієнта
- Оновлення email (якщо поле існує в таблиці)

Опціонально, якщо вам хочеться більше практики:
- Логування змін в окрему таблицю

Використайте підхід з параметризованими запитами через `text()` та `UPDATE` оператор. Не забудьте на початку перевірити чи існує клієнт з таким номером в базі - це хороша практика.

Отримати всі колонки, які існують в таблиці ви можете наступним запитом
```
  SELECT COLUMN_NAME, DATA_TYPE
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'customers'
```

Запустіть функцію і продемонструйте її роботу, запустивши SELECT, який допоможе це зробити.

In [58]:
pip install sqlalchemy pymysql pandas matplotlib seaborn python-dotenv --quiet

Note: you may need to restart the kernel to use updated packages.

In [59]:
import datetime
import requests
import json
import os

from dotenv import load_dotenv
import pandas as pd
import sqlalchemy as sa
from sqlalchemy import create_engine, text, MetaData, Table
from sqlalchemy.orm import sessionmaker

In [60]:
def create_connection():
    """
    Створює підключення через SQLAlchemy
    """
    # Завантажуємо змінні середовища
    load_dotenv()

    # Отримуємо параметри з environment variables
    host = os.getenv('DB_HOST', 'localhost')
    port = os.getenv('DB_PORT', '3306')
    user = os.getenv('DB_USER')
    password = os.getenv('DB_PASSWORD')
    database = os.getenv('DB_NAME')

    if not all([user, password, database]):
        raise ValueError("Не всі параметри БД задані в .env файлі!")

    # Створюємо connection string
    connection_string = f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}"

    # Створюємо engine з connection pooling
    engine = create_engine(
        connection_string,
        pool_size=2,           # Розмір пулу підключень
        max_overflow=20,        # Максимальна кількість додаткових підключень
        pool_pre_ping=True,     # Перевірка підключення перед використанням
        echo=False              # Логування SQL запитів (True для debug)
    )

    # Тестуємо підключення
    try:
        with engine.connect() as conn:
            result = conn.execute(text("SELECT 1"))
            result.fetchone()

        print("✅ Підключення до БД успішне!")
        print(f"🔗 {user}@{host}:{port}/{database}")
        print(f"⚡ Engine: {engine}")

        return engine

    except Exception as e:
        print(f"❌ Помилка підключення: {e}")
        return None

# Створюємо підключення
engine = create_connection()

✅ Підключення до БД успішне!
🔗 root@127.0.0.1:3306/classicmodels
⚡ Engine: Engine(mysql+pymysql://root:***@127.0.0.1:3306/classicmodels)

In [61]:
def customer_info_update(engine, customerNumber, new_phone, new_email):
    """
    Оновлення номеру телефона/електронної пошти клієнта з використанням транзакції
    """

    # Спочатку перевіряємо чи існує клієнт (окремо від транзакції)
    check_query = text("SELECT contactFirstName, contactLastName FROM customers WHERE customerNumber = :customerNumber")

    with engine.connect() as conn:
        result = conn.execute(check_query, {'customerNumber': customerNumber})
        customer = result.fetchone()

        if not customer:
            print(f"❌ Клієнт {customerNumber} не знайдений")
            return False

        name = f"{customer[0]} {customer[1]}"
        print(f"👤 Оновлюємо дані клієнта на ім'я {name} (ID: {customerNumber})")

    # Тепер створюємо нове підключення для транзакції
    with engine.connect() as conn:
        with conn.begin():
            try:
                check_column_query = text("""
                    SELECT COLUMN_NAME, DATA_TYPE
                    FROM INFORMATION_SCHEMA.COLUMNS
                    WHERE TABLE_NAME = 'customers' AND COLUMN_NAME = :columnName
                """)

                resultColumn = conn.execute(check_column_query, {'columnName': 'phone'})
                resultPhoneColumn = resultColumn.fetchone()

                if resultPhoneColumn:
                    # Крок 1: Оновлюємо номер телефону
                    update_phone_query = text("""
                        UPDATE customers
                        SET phone = :new_phone
                        WHERE customerNumber = :customerNumber
                    """)

                    result1 = conn.execute(update_phone_query, {'new_phone': new_phone, 'customerNumber': customerNumber})
                    print(f"✅ Крок 1: Оновлено телефон (оновлено {result1.rowcount} записів)")
                else:
                    print("Phone column doesn't exists")

                resultColumn = conn.execute(check_column_query, {'columnName': 'email'})
                resultEmailColumn = resultColumn.fetchone()

                if resultEmailColumn:
                    # Крок 2: Оновлюємо електронну пошту
                    update_email_query = text("""
                        UPDATE customers
                        SET email = :new_email
                        WHERE customerNumber = :customerNumber
                    """)

                    result1 = conn.execute(update_email_query, {'new_email': new_email, 'customerNumber': customerNumber})
                    print(f"✅ Крок 2: Оновлено пошту (оновлено {result1.rowcount} записів)")
                else:
                    print("Email column doesn't exists")

                # print("✅ Всі кроки виконано успішно!")
                # if column:
                    # update_email_query = text("""""")

                return True

            except Exception as e:
                # conn.rollback()
                print(f"❌ Помилка при оновленні: {e}")
                print("🔄 Всі зміни автоматично скасовано (ROLLBACK)")
                return False

In [62]:
customerNumber = 112

# Дивимось поточну інформацію про співробітника
check_result_query = text("""
    SELECT
       customerNumber,                      
       contactFirstName,
       contactLastName,
       phone
   FROM customers 
   WHERE customerNumber = :customerNumber
   """)

df_result_pre = pd.read_sql(check_result_query, engine, params={'customerNumber': customerNumber})

# Тестуємо оновлення даних клієнта

success = customer_info_update(
    engine,
    customerNumber,
    new_phone=1234567898,
    new_email='iii@gmail.com'
)

df_result_after = pd.read_sql(check_result_query, engine, params={'customerNumber': customerNumber})

print("Поточний телефон клієнта:")
display(df_result_pre)
print("Оновлений телефон клієнта:")
display(df_result_after)

👤 Оновлюємо дані клієнта на ім'я Jean King (ID: 112)
✅ Крок 1: Оновлено телефон (оновлено 1 записів)
Email column doesn't exists
Поточний телефон клієнта:

   customerNumber contactFirstName contactLastName       phone
0             112             Jean            King  1234567898

Оновлений телефон клієнта:

   customerNumber contactFirstName contactLastName       phone
0             112             Jean            King  1234567898

In [63]:
# Дивимось поточну інформацію про співробітника
check_result_query = text("""
    SELECT
       customerNumber,                      
       contactFirstName,
       contactLastName,
       phone
   FROM customers 
   WHERE customerNumber = :customerNumber
   """)

df_result = pd.read_sql(check_result_query, engine, params={'customerNumber': customerNumber})
print("Поточний телефон клієнта:")
display(df_result)

Поточний телефон клієнта:

   customerNumber contactFirstName contactLastName       phone
0             112             Jean            King  1234567898

### Завдання 2: Створення нового замовлення з транзакцією (5 балів)

**Реалізуйте процес створення нового замовлення** з наступними кроками в одній транзакції:
- Створення запису в таблиці `orders`
- Додавання товарних позицій в `orderdetails`
- Перевірка наявності товарів на складі
- Зменшення кількості товарів на складі

Запустіть процес з тестовими даними і продемонструйте через SELECT, що процес успішно відпрацював і були виконані необхідні операції.

In [70]:
new_order = {
    'orderNumber': 12225,  
    'orderDate': '2006-06-06',
    'requiredDate': '2006-07-20',
    'shippedDate': '2006-06-10',
    'status': 'Shipped',
    'comments': 'Customer is satisfied',
    'customerNumber': 146  
}

orderdetails = [
    {'productCode': 'S50_1392', 'quantityOrdered': 1, 'priceEach': 100.7},
    {'productCode': 'S72_3212', 'quantityOrdered': 1, 'priceEach': 51.32},
]

with engine.connect() as conn:
    with conn.begin():  

        conn.execute(
            text("""
                INSERT INTO orders
                (orderNumber, orderDate, requiredDate, shippedDate, status, comments, customerNumber)
                VALUES
                (:orderNumber, :orderDate, :requiredDate, :shippedDate, :status, :comments, :customerNumber)
            """),
            new_order
        )

        for idx, item in enumerate(orderdetails, start=1):  

            stock = conn.execute(
                text("SELECT quantityInStock FROM products WHERE productCode = :productCode"),
                {'productCode': item['productCode']}
            ).scalar()

            if stock < item['quantityOrdered']:
                raise Exception(f"Недостатньо товару на складі для {item['productCode']}. На складі: {stock}")

            conn.execute(
                text("""
                    INSERT INTO orderdetails
                    (orderNumber, productCode, quantityOrdered, priceEach, orderLineNumber)
                    VALUES
                    (:orderNumber, :productCode, :quantityOrdered, :priceEach, :orderLineNumber)
                """),
                {
                    'orderNumber': new_order['orderNumber'],
                    'orderLineNumber': idx,
                    **item
                }
            )

            conn.execute(
                text("""
                    UPDATE products
                    SET quantityInStock = quantityInStock - :quantityOrdered
                    WHERE productCode = :productCode
                """),
                item
            )

print(f"✅ Замовлення #{new_order['orderNumber']} створене.")

✅ Замовлення #12225 створене.

In [73]:
with engine.connect() as conn:

    check_result_order_df = pd.read_sql(
        text("SELECT * FROM orders WHERE orderNumber = :orderNumber"),
        conn,
        params={'orderNumber': new_order['orderNumber']}
    )
    print("Замовлення:")
    display(check_result_order_df)

    check_result_orderdetails_df = pd.read_sql(
        text("""
            SELECT * FROM orderdetails
            WHERE orderNumber = :orderNumber
            ORDER BY orderLineNumber
        """),
        conn,
        params={'orderNumber': new_order['orderNumber']}
    )
    print("Товарні позиції:")
    display(check_result_orderdetails_df)

    product_codes = [item['productCode'] for item in orderdetails]
    products_df = pd.read_sql(
        text("""
            SELECT productCode, productName, quantityInStock
            FROM products
            WHERE productCode IN :codes
        """),
        conn,
        params={'codes': tuple(product_codes)}
    )
    print("Залишок товарів на складі:")
    display(products_df)

Замовлення:

,orderNumber,orderDate,requiredDate,shippedDate,status,comments,customerNumber
0,12225,2006-06-06,2006-07-20,2006-06-10,Shipped,Customer is satisfied,146

Товарні позиції:

   orderNumber productCode  quantityOrdered  priceEach  orderLineNumber
0        12225    S50_1392                1     100.70                1
1        12225    S72_3212                1      51.32                2

Залишок товарів на складі:

  productCode                       productName  quantityInStock
0    S50_1392  Diamond T620 Semi-Skirted Tanker             1012
1    S72_3212                        Pont Yacht              410